# fleet setup for interactive local test
version: '2'
services:
  rating:
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./test/config:/config
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - ./test/initdb.d:/docker-entrypoint-initdb.d
      - ./schema.sql:/docker-entrypoint-initdb.d/10-schema.sql
    environment:
      - POSTGRES_USER=rating
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=rating